### ISSUE TITLE
Add GitHub.io site

### ISSUE THREAD

**Issue by sarob** [not-that-metaDAO/MTOTM#3]
Add GitHub.io page to repo for PR of project strategy and user doc

**Comment by sarob** [comment]
commit [337ac3a](https://github.com/not-that-metaDAO/MTOTM/commit/337ac3a187784659a951ece3692220afaa818edc) partly implements this issue

**Comment by epowell101** [comment]
Is this a Github pages that we are after?  I think that is what we mean by a github.io site, right?
https://pages.github.com/

**Comment by sarob** [comment]
Yes, that’s the explanation of how it works. The site url will be https://not-that-metadao.github.io by default. Sean ***@***.*** On Oct 7, 2022, at 08:02, Evan Powell LLC ***@***.***> wrote:﻿
Is this a Github pages that we are after?  I think that is what we mean by a github.io site, right?
https://pages.github.com/

**Comment by sarob** [comment]
Seems the last commit action took the root README instead of the docs/index.md. I'll investigate.

**Comment by sarob** [comment]
It was a GitHub action error. Solved.

**Comment by sarob** [comment]
Io page created. More updated to the status website to follow. This first step is completed.
